name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cli/gh-extension-precompile@9e2237c30f869ad3bcaed6a4be2cd43564dd421b # v2.1.0
        with:
          build_script_override: "./scripts/build.sh"

  release-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable @ 2025-12-08
        with:
          targets: x86_64-apple-darwin,aarch64-apple-darwin
      - name: Build for Intel macOS
        run: bash ./scripts/build.sh
        env:
          TARGET_TRIPLE: x86_64-apple-darwin
          OS_ARCH: darwin-amd64
      - name: Build for Apple Silicon macOS
        run: bash ./scripts/build.sh
        env:
          TARGET_TRIPLE: aarch64-apple-darwin
          OS_ARCH: darwin-arm64
      - name: Upload release artifact
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          draft: false
          prerelease: false
          files: |
            dist/darwin-amd64
            dist/darwin-arm64

  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable @ 2025-12-08
        with:
          targets: x86_64-pc-windows-msvc
      - name: Build for x86_64 Windows
        run: bash ./scripts/build.sh
        env:
          TARGET_TRIPLE: x86_64-pc-windows-msvc
          OS_ARCH: windows-amd64.exe
      - name: Upload release artifact
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          draft: false
          prerelease: false
          files: |
            dist/windows-amd64.exe
